### PR TITLE
New developments

### PR DESCRIPTION
**Pull request by jkhoeini**
@saeedSarpas @pouria-k 
Here is the the recent updates that I made regarding docker and other things.
Also I merged develop here to master, so further development takes place directly on master.

Also, I updated the README with docker instructions.

### CODE REVIEW

**Comment by saeedSarpas** [comment]
Cool.. I guess from now on we couldn't use travis anymore. right?

btw, nice job, :sheep: it

**Comment by mkhoeini** [comment]
Nothing regarding Travis-ci has changed.
I guess we should take two :shipit:s from now on! :D

**Comment by pouria-k** [comment]
Guys, thank you for adding me to the whole :sheep: it process. I will have a look and give you my feedback.

As my first comment, I think 76 commits per pull request is a lot. Do you agree @mkhoeini?

**Comment by mkhoeini** [comment]
@pouria-k Yes, it is a lot. This is the result of our previous branch management. This is the accumulated work since we last merged develop to master. i.e. the sum of many pull requests.
Actually this pull request consists solely the last 11 commits made by me. The rest had been merged previously on the develop branch.

**Comment by pouria-k** [comment]
:sheep:  it mate.

**Pull request merged**
